version: '3'
services:
  mysql:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
      TZ: ${DB_TZ}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./databases/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    restart: always
volumes:
  mysql_data:
    driver: local
